PRIMARY_PURPLE = "#8B5CF6"
PRIMARY_LAVENDER = "#A78BFA"
LIGHT_PURPLE = "#C4B5FD"
DARK_PURPLE = "#7C3AED"

SECONDARY_PURPLE = "#9F7AEA"
SECONDARY_LAVENDER = "#B794F4"
SECONDARY_LIGHT = "#DDD6FE"
SECONDARY_DARK = "#6B46C1"

NEUTRAL_GRAY = "#6B7280"
LIGHT_GRAY = "#F3F4F6"
DARK_GRAY = "#374151"

CHART_COLORS = [
    PRIMARY_PURPLE,
    PRIMARY_LAVENDER,
    SECONDARY_PURPLE,
    SECONDARY_LAVENDER,
    SECONDARY_LIGHT,
    LIGHT_PURPLE,
    DARK_PURPLE,
    SECONDARY_DARK
]

# Paleta para métricas específicas
METRIC_COLORS = {
    'success': SECONDARY_PURPLE,
    'warning': SECONDARY_DARK,
    'error': DARK_PURPLE,
    'info': PRIMARY_LAVENDER,
    'primary': PRIMARY_PURPLE,
    'secondary': PRIMARY_LAVENDER
}

# Paleta para tecnologias
TECH_COLORS = {
    'GHC': PRIMARY_PURPLE,
    'MANUAL': DARK_PURPLE,
    'GPS': PRIMARY_LAVENDER,
    'DEFAULT': NEUTRAL_GRAY
}
